name: Publish stable release of PizzaTowerModTool GUI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_gui:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: win-x64
            output_name: Windows
            singlefile: true
          - os: windows-latest
            target: win-x64
            output_name: Windows-SingleFile
            singlefile: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build PizzaTowerModTool (${{ matrix.target }})
      run: |
        dotnet build UndertaleModTool --no-restore -c Release -r ${{ matrix.target }}

    - name: Publish PizzaTowerModTool (${{ matrix.target }})
      run: |
        dotnet publish UndertaleModTool -c Release -r ${{ matrix.target }} --self-contained true -p:PublishSingleFile=${{ matrix.singlefile }} --output ./${{ matrix.output_name }}

    - name: Copy external files
      shell: pwsh
      run: |
        if (Test-Path ./README.md) { Copy-Item ./README.md ./${{ matrix.output_name }}/ -Force }
        if (Test-Path ./SCRIPTS.md) { Copy-Item ./SCRIPTS.md ./${{ matrix.output_name }}/ -Force }
        if (Test-Path ./LICENSE.txt) { Copy-Item ./LICENSE.txt ./${{ matrix.output_name }}/ -Force }
        if (Test-Path ./${{ matrix.output_name }}/Underanalyzer.pdb) { Remove-Item ./${{ matrix.output_name }}/Underanalyzer.pdb -Force }

    - name: Create ZIP Artifact
      shell: pwsh
      run: |
        Compress-Archive -Path ./${{ matrix.output_name }}/* -DestinationPath PizzaTowerModTool-GUI-${{ matrix.output_name }}.zip -Force

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
          name: PizzaTowerModTool-GUI-${{ matrix.output_name }}
          path: PizzaTowerModTool-GUI-${{ matrix.output_name }}.zip
          archive: false
